OS:
  ULC_deb:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "ubuntu18.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      ARCH:
        - x86_64
  MacOS:
    "10.13.6":
      TYPE: macos
      ARCH:
        - x64
